# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='ques',
        ),
    ]
