# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20180413_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(upload_to='static/image/', verbose_name='img'),
        ),
    ]
