# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 14:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_auto_20180509_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=tinymce.models.HTMLField(),
        ),
    ]
