# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-14 15:41
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_question_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
