# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-16 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_question_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commented_on']},
        ),
    ]
